//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StickFight.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("37")]
        public int Plr1Left {
            get {
                return ((int)(this["Plr1Left"]));
            }
            set {
                this["Plr1Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("38")]
        public int Plr1Up {
            get {
                return ((int)(this["Plr1Up"]));
            }
            set {
                this["Plr1Up"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("39")]
        public int Plr1Right {
            get {
                return ((int)(this["Plr1Right"]));
            }
            set {
                this["Plr1Right"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int Plr1Down {
            get {
                return ((int)(this["Plr1Down"]));
            }
            set {
                this["Plr1Down"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("188")]
        public int Plr1Hit {
            get {
                return ((int)(this["Plr1Hit"]));
            }
            set {
                this["Plr1Hit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("189")]
        public int Plr1Kick {
            get {
                return ((int)(this["Plr1Kick"]));
            }
            set {
                this["Plr1Kick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("190")]
        public int Plr1Block {
            get {
                return ((int)(this["Plr1Block"]));
            }
            set {
                this["Plr1Block"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65")]
        public int Plr2Left {
            get {
                return ((int)(this["Plr2Left"]));
            }
            set {
                this["Plr2Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("87")]
        public int Plr2Up {
            get {
                return ((int)(this["Plr2Up"]));
            }
            set {
                this["Plr2Up"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("68")]
        public int Plr2Right {
            get {
                return ((int)(this["Plr2Right"]));
            }
            set {
                this["Plr2Right"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("83")]
        public int Plr2Down {
            get {
                return ((int)(this["Plr2Down"]));
            }
            set {
                this["Plr2Down"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("69")]
        public int Plr2Hit {
            get {
                return ((int)(this["Plr2Hit"]));
            }
            set {
                this["Plr2Hit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("81")]
        public int Plr2Kick {
            get {
                return ((int)(this["Plr2Kick"]));
            }
            set {
                this["Plr2Kick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("82")]
        public int Plr2Block {
            get {
                return ((int)(this["Plr2Block"]));
            }
            set {
                this["Plr2Block"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
                    ##
                   ##
                   ##              Welcome to StickFight
                  ##
                 /##\
   .##.        .####-####################################################..
  <################|#|#                                                 #####
   '##'        '####-####################################################''
                 \##/
                  ##
                   ##               Get ready to fight!
                   ##
                    ##
")]
        public string EntryScreen {
            get {
                return ((string)(this["EntryScreen"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("╔══════════════════════════════════════════════════════════════════════════════╗\r" +
            "\n║                                                                              " +
            "║\r\n║                                                                            " +
            "  ║\r\n║                                                                          " +
            "    ║\r\n║                                                                        " +
            "      ║\r\n║                                                                      " +
            "        ║\r\n║                                                                    " +
            "          ║\r\n║                                                                  " +
            "            ║\r\n║                                                                " +
            "              ║\r\n║                                                              " +
            "                ║\r\n║                                                            " +
            "                  ║\r\n║                                                          " +
            "                    ║\r\n║                                                        " +
            "                      ║\r\n║                                                      " +
            "                        ║\r\n║                                                    " +
            "                          ║\r\n║                                                  " +
            "                            ║\r\n║                                                " +
            "                              ║\r\n║                                              " +
            "                                ║\r\n║                                            " +
            "                                  ║\r\n║                                          " +
            "                                    ║\r\n║                                        " +
            "                                      ║\r\n║                                      " +
            "                                        ║\r\n║                                    " +
            "                                          ║\r\n║                                  " +
            "                                            ║\r\n║                                " +
            "                                              ║\r\n╚══════════════════════════════" +
            "════════════════════════════════════════════════╝")]
        public string StandardMap {
            get {
                return ((string)(this["StandardMap"]));
            }
        }
    }
}
